server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/bookstore1}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/bookstore1}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 30000
      maximum-pool-size: 10


  jpa:
#    hibernate:
#      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
#    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      defer-datasource-initialization: true

jwt:
  signer-key: ${JWT_SIGNER_KEY}
  valid-duration: ${JWT_VALID_DURATION:360000}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:36000}

app:
  bootstrap:
    admin:
      enabled: ${APP_BOOTSTRAP_ADMIN_ENABLED:true}
      email: ${APP_BOOTSTRAP_ADMIN_EMAIL:}
      password: ${APP_BOOTSTRAP_ADMIN_PASSWORD:}
      full-name: ${APP_BOOTSTRAP_ADMIN_FULL_NAME:Administrator}
