CREATE TABLE IF NOT EXISTS `review` (
  `id` binary(16) NOT NULL,
  `book_id` binary(16) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `rating` int NOT NULL,
  `content` varchar(2000) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'APPROVED',
  `verified_purchase` bit(1) NOT NULL DEFAULT b'0',
  `admin_reply` varchar(2000) DEFAULT NULL,
  `customer_reply` varchar(2000) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `replied_at` datetime(6) DEFAULT NULL,
  `customer_replied_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_review_book_id` (`book_id`),
  KEY `idx_review_user_id` (`user_id`),
  KEY `idx_review_status` (`status`),
  CONSTRAINT `fk_review_book` FOREIGN KEY (`book_id`) REFERENCES `book` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_review_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
